---
abstract: 'Module to syntax check a Perl program file or exec string.'
author:
  - 'Rocky Bernstein <rocky@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.32
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Syntax
provides:
  Perl::Syntax:
    file: lib/Perl/Syntax.pm
    version: 1.00
requires:
  perl: 5.008008
  rlib: 0.02
  version: 0
resources:
  bugtracker: https://github.com/rocky/Perl-Syntax/issues
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
  repository: http://github.com/rocky/Perl-Syntax
version: 1.00
